# Generated by Django 4.1.2 on 2022-11-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(blank=True, max_length=35, null=True)),
                ('blogContent', models.TextField(blank=True, null=True)),
                ('dateModified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
