# Generated by Django 4.1.2 on 2022-11-04 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogger',
            name='blogUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogger',
            name='userType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usertag'),
        ),
    ]
