# Generated by Django 4.1.2 on 2022-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usertag_alter_blogger_bloguser_blogger_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='maxPost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
