# Generated by Django 4.1.2 on 2022-11-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usertag_maxpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='canEdit',
            field=models.BooleanField(default=False),
        ),
    ]
