# Generated by Django 4.1.2 on 2022-11-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usertag_canedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
