# Generated by Django 4.1.2 on 2022-11-06 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blog_isapproved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorReqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.blogger')),
            ],
        ),
    ]
