# Generated by Django 4.1.2 on 2022-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_supervisorreqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorreqs',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
    ]
